name: math_buddies
description: "Playful math adventures for little learners!"
publish_to: "none"
version: 1.1.3+5

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
